### ISSUE TITLE
add movie.cast as part of const movieInfo, so that we can search certain actors and actresses in the keywords section.

### ISSUE THREAD

**Issue by CJFeagin33** [matthkang/Movie-Finder#25]

**Comment by chinosj89** [comment]
information to append to results.html added for cast. 
![image](https://github.com/matthkang/Movie-Finder/assets/131737817/8693e517-985f-4814-b51b-78fc0159a44a)

changes pushed and pending merge in Results-JS-Feature-Branch 
review pending by @matthkang

**Comment by chinosj89** [comment]
entire cast shows now regardless of how many are within the object
