### ISSUE TITLE
fetch youtube api

### ISSUE THREAD

**Issue by CJFeagin33** [matthkang/Movie-Finder#6]
Use movie of the night api -> returns title (keyword)
Use titles to search for video with youtube search API (https://developers.google.com/youtube/v3/docs/search/list) (add trailer to end of keyword, and use maxResult = 1) -> returns distinct video id
Use Id to put into iframe html element as src parameter

**Comment by CJFeagin33** [comment]
search for movie title + "trailer" through the youtube api on our results page

**Comment by chinosj89** [comment]
![Image](https://github.com/matthkang/Movie-Finder/assets/131737817/a82d3537-0723-4bf5-ab8f-4e46a8a6a023)

adding comment

fetch done by @matthkang

**Comment by chinosj89** [comment]
@matthkang was able to link the youtube api using aysnc/await


![Image](https://github.com/matthkang/Movie-Finder/assets/131737817/1b319dcf-3801-4f1b-9bea-d2dfb613085b)
